enum COMMANDS {
  PLAY = "PLAY",
  SEARCH = "SEARCH",
  PAUSE = "PAUSE",
  RESUME = "RESUME",
  SKIP = "SKIP",
  STOP = "STOP",
  SKIP_PLAYLIST = "SKIPLIST",
  QUEUE = "QUEUE",
  HELP = "HELP",
  ADD_PLAYLIST = "PLAYLIST",
}

export default COMMANDS;
